/* Original Source Ported From https://github.com/adafruit/Adafruit_NeoPixel */
/* (Adafruit_NeoPixel's rp2040_pio.h, itself autogenerated by pioasm from pico-examples) */
/*
BSD 3-Clause License

Copyright (c) 2022, Darren Horrocks
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

// Precompiled PIO program (not hand-editable) that shifts out one bit per
// loop, using side-set to produce the WS2812 one-wire waveform. One byte is
// pushed to the TX FIFO per pio_sm_put_blocking() call, shifted to the top
// 8 bits, regardless of whether the strip is RGB (3 bytes/pixel) or RGBW
// (4 bytes/pixel) -- the program itself is colour-format agnostic.

#ifndef __WS2812_PIO_PROGRAM_H__
#define __WS2812_PIO_PROGRAM_H__

#include "hardware/pio.h"
#include "hardware/clocks.h"

#define ws2812_wrap_target 0
#define ws2812_wrap 3

#define ws2812_T1 2
#define ws2812_T2 5
#define ws2812_T3 3

static const uint16_t ws2812_program_instructions[] = {
    //     .wrap_target
    0x6221, //  0: out    x, 1            side 0 [2]
    0x1123, //  1: jmp    !x, 3           side 1 [1]
    0x1400, //  2: jmp    0               side 1 [4]
    0xa442, //  3: nop                    side 0 [4]
            //     .wrap
};

static const struct pio_program ws2812_program = {
    .instructions = ws2812_program_instructions,
    .length = 4,
    .origin = -1,
};

static inline pio_sm_config ws2812_program_get_default_config(uint offset)
{
   pio_sm_config c = pio_get_default_sm_config();
   sm_config_set_wrap(&c, offset + ws2812_wrap_target, offset + ws2812_wrap);
   sm_config_set_sideset(&c, 1, false, false);
   return c;
}

static inline void ws2812_program_init(PIO pio, uint sm, uint offset, uint pin, float freq)
{
   pio_gpio_init(pio, pin);
   pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, true);

   pio_sm_config c = ws2812_program_get_default_config(offset);
   sm_config_set_sideset_pins(&c, pin);
   sm_config_set_out_shift(&c, false, true, 8);
   sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_TX);

   int cycles_per_bit = ws2812_T1 + ws2812_T2 + ws2812_T3;
   float div = clock_get_hz(clk_sys) / (freq * cycles_per_bit);
   sm_config_set_clkdiv(&c, div);

   pio_sm_init(pio, sm, offset, &c);
   pio_sm_set_enabled(pio, sm, true);
}

#endif // __WS2812_PIO_PROGRAM_H__
